spring.application.name=backend

1. Conexion a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/arcade_dev
spring.datasource.username=root
spring.datasource.password=root

1. Configuracion de JPA y visualizacion en consola
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true